name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        npm install

    - name: Build Next.js app
      run: |
        npm run build

    - name: Set Git user
      run: |
        git config --global user.email "shamsuddohamiazy@gmail.com"
        git config --global user.name "Shams-Ud-Doha"

    - name: Deploy to GitHub Pages
      run: |
        npm install --save-dev gh-pages
        npm run deploy

